# stage 1 using latest GraalVM for java 21 as per https://github.com/graalvm/container/pkgs/container/graalvm-community
FROM ghcr.io/graalvm/native-image-community:21-muslib AS builder

# build directory
WORKDIR /build

# copy source code into directory
COPY . /build

# maven install in the root of project and native compile webserver directory
RUN ./mvnw clean install -DskipTests \
    && cd webserver/ \
    && ./mvnw --no-transfer-progress -Pnative native:compile -DskipTests

# Stage 2
FROM gcr.io/distroless/static-debian12

# copy generated bytecode from target directory
COPY --from=builder /build/webserver/target/webserver ./

# entry point to run bytecode
CMD ["./webserver"]
