### Test
GET http://localhost:1997/test/all


### Client register
POST http://localhost:1997/api/v1/client/auth/register
Content-Type: application/json

{
  "firstname": "firstname",
  "lastname": "Development",
  "email": "yes@yes.com",
  "username": "frank white",
  "phone_number": "000-000-0000",
  "password": "123#-SEJU-Development"
}


### Client Login
POST http://localhost:1997/api/v1/client/auth/login
Content-Type: application/json

{
 "principal":"yes@yes.com",
 "password":"123#-SEJ-Development"
}


### Worker register
POST http://localhost:1997/api/v1/worker/auth/register
Content-Type: application/json

{
  "name": "firstname",
  "username": "Development",
  "email": "admin@yes.com",
  "password": "123#-SEJU-Development"
}


### Worker Login
POST http://localhost:1997/api/v1/worker/auth/login
Content-Type: application/json

{
  "principal":"admin@yes.com",
  "password":"123#-SEJU-Development"
}