### Test
GET http://localhost:1997/test/all


### Client register
POST http://localhost:1997/api/v1/client/auth/register
Content-Type: application/json

{
  "firstname": "firstname",
  "lastname": "Development",
  "email": "yes@yes.com",
  "username": "frank white",
  "phone_number": "000-000-0000",
  "password": "123#-SEJU-Development"
}


### Client Login
POST http://localhost:1997/api/v1/client/auth/login
Content-Type: application/json

{
  "principal":"yes@yes.com",
  "password":"123#-SEJ-Development"
}


### Worker register
POST http://localhost:1997/api/v1/worker/auth/register
Content-Type: application/json

{
  "name": "firstname",
  "username": "Development",
  "email": "admin@yes.com",
  "password": "123#-SEJU-Development"
}


### Worker Login
POST http://localhost:1997/api/v1/worker/auth/login
Content-Type: application/json

{
  "principal":"admin@admin.com",
  "password":"password123"
}


### Delete a product
DELETE http://localhost:1997/api/v1/worker/product/Aerodynamic Concrete Watch/3e50943c-c9e5-490c-88df-464dd2ff2bb6


### Get All Products Client
GET http://localhost:1997/api/v1/client/category/products?category_id=5