### Client register
POST http://localhost:1997/api/v1/auth/client/register
Content-Type: application/json

{
  "firstname": "firstname",
  "lastname": "Development",
  "email": "yes@yes.com",
  "phone_number": "000-000-0000",
  "password": "123#-SEJU-Development"
}


### Client Login
POST http://localhost:1997/api/v1/auth/client/login
Content-Type: application/json

{
 "principal":"yes@yes.com",
 "password":"123#-SEJU-Development"
}
