server:
  port: ${SERVER_PORT:1997}
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: on_param
  servlet:
    application-display-name: 'Capstone Api'
    session:
      tracking-modes: cookie
      cookie:
        http-only: true
        name: JSESSIONID
        path: /
        same-site: lax
        max-age: 18000
        secure: true
  forward-headers-strategy: native
  tomcat:
    redirect-context-root: false

logging:
  level:
    org:
      hibernate: error
      springframework:
        jdbc: trace
        security: trace

spring:
  application:
    name: 'Capstone Api'
  threads:
    virtual:
      enabled: true
  profiles:
    active: default
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/capstone_db}
    username: ${SPRING_DATASOURCE_USERNAME:capstone}
    password: ${SPRING_DATASOURCE_PASSWORD:capstone}
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-description: init
    baseline-version: 0
    table: flyway_schema_history
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
      close-closeable: true
      flush-after-write-value: true
      write-date-keys-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
  servlet:
    multipart:
      max-file-size: 6MB
      max-request-size: 10MB
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:google-client-secret}
            redirectUri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - profile
              - email
              - openid
  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    protocol: smtp
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME:test}
    password: ${SPRING_MAIL_PASSWORD:mail-password}
    default-encoding: UTF-8
    properties:
      "[mail.mime.charset]": UTF
      "[mail.smtp.connectiontimeout]": 5000 # 5 secs
      "[mail.smtp.timeout]": 5000
      "[mail.smtp.writetimeout]": 5000
      "[mail.smtp.auth]": true
      "[mail.smtp.starttls.enable]": true
      "[mail.smtp.starttls.required]": true
    application:
      contact-email: developer@email.com

management:
  endpoints:
    web:
      exposure:
        include: 'health,info'
      base-path: /api/v1/actuator

api:
  endpoint:
    baseurl: ${API_PREFIX:api/v1/}

user:
  principal: ${USER_PRINCIPAL:admin@admin.com}

paystack:
  pub:
    key: ${PAYSTACK_PUB_KEY:paystack-pub}
  secret:
    key: ${PAYSTACK_SECRET_KEY:paystack-secret}

cors:
  ui:
    domain: http://localhost:4200/

aws:
  bucket: development

application:
  log:
    webhook:
      discord: discord

cart:
  cookie:
    name: CARTCOOKIE
  split: '%'

capstone:
  usd:
    to:
      cent: 100
  ngn:
    to:
      kobo: 0.34

race-condition:
  expiration:
    bound: 900
shopping:
  session:
    expiration:
      bound: 18000