CREATE TABLE IF NOT EXISTS child_entity (
    child_id BIGINT NOT NULL UNIQUE AUTO_INCREMENT,
    name VARCHAR(255),
    PRIMARY KEY (child_id)
);

CREATE TABLE IF NOT EXISTS test_entity (
    id BIGINT NOT NULL UNIQUE AUTO_INCREMENT,
    name VARCHAR(255) UNIQUE NOT NULL,
    sku VARCHAR(255) UNIQUE NOT NULL,
    child_id BIGINT,
    PRIMARY KEY (id),
    FOREIGN KEY (child_id) REFERENCES child_entity(child_id)
);